/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./../components/card/index.vue')['default']
    CustomPagination: typeof import('./../components/CustomPagination/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Login: typeof import('./../components/login/index.vue')['default']
    Menu: typeof import('./../components/menu/index.vue')['default']
    MonacoEditor: typeof import('./../components/monaco-editor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
