/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"local-dept" | "local-menu" | "local-notice" | "local-role" | "local-theme">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"local-dept" | "local-menu" | "local-notice" | "local-role" | "local-theme">;
          default: string;
          required: true;
      };
  }>>, {
      name: "local-dept" | "local-menu" | "local-notice" | "local-role" | "local-theme";
  }>;
  export const svgNames: ["local-dept", "local-menu", "local-notice", "local-role", "local-theme"];
  export type SvgName = "local-dept" | "local-menu" | "local-notice" | "local-role" | "local-theme";
  export default SvgIcon;
}
